spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:admin_videos_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;
    username: root
    password: 123456
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2